##### Siddhant Pardeshi | Roll Number: 37 | ML 2

#### Problem Statement

Classify the email using the binary classification method.<br> 
Email Spam detection has two states: <br> 
a) Normal State – Not Spam, b) Abnormal State – Spam.
<br>Use K-Nearest Neighbors and Support Vector Machine for classification. Analyze their performance.

In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
%matplotlib inline

In [39]:
data = pd.read_csv('DATASET/emails.csv')

In [40]:
data.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [41]:
data.isna().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

Splitting the dataset

In [42]:
# Input Data
x = data.iloc[:,1:3001]

# Output Data
y = data.iloc[:, -1].values

In [43]:
print(x.shape)
print(y.shape)

(5172, 3000)
(5172,)


In [44]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.25, random_state=5)

print("xtrain shape: ", xtrain.shape)
print("xtest shape: ", xtest.shape)
print("ytrain shape: ", ytrain.shape)
print("ytest shape: ", ytest.shape)

xtrain shape:  (3879, 3000)
xtest shape:  (1293, 3000)
ytrain shape:  (3879,)
ytest shape:  (1293,)


In [45]:
from sklearn.neighbors import KNeighborsClassifier  
model = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)  
model.fit(xtrain, ytrain)

KNeighborsClassifier()

In [46]:
ypred = model.predict(xtest)
ypred

array([0, 0, 1, ..., 0, 1, 1], dtype=int64)

#### Confusion Matrix

In [47]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest, ypred)
cm

array([[790, 100],
       [ 67, 336]], dtype=int64)

<b> This CM tells us that 1126 predictions were correct and 167 were incorrect, meaning the model has a high accuracy of 87%

In [52]:
from sklearn.metrics import classification_report
cr = classification_report(ytest, ypred)
print(cr)

              precision    recall  f1-score   support

           0       0.92      0.89      0.90       890
           1       0.77      0.83      0.80       403

    accuracy                           0.87      1293
   macro avg       0.85      0.86      0.85      1293
weighted avg       0.87      0.87      0.87      1293



### <b> Support Vector Machine

In [48]:
from sklearn.svm import SVC  
SVCmodel = SVC(kernel='linear', random_state=0)  
SVCmodel.fit(xtrain, ytrain)  

SVC(kernel='linear', random_state=0)

In [49]:
y_pred = SVCmodel.predict(xtest)
y_pred

array([0, 0, 1, ..., 0, 1, 1], dtype=int64)

Confusion Matrix

In [50]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest, y_pred)
cm

array([[870,  20],
       [ 29, 374]], dtype=int64)

<b> This CM tells us that 1244 predictions were correct and 49 were incorrect, meaning the model has a high accuracy of 96.2%

In [53]:
from sklearn.metrics import classification_report
cr = classification_report(ytest, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.97      0.98      0.97       890
           1       0.95      0.93      0.94       403

    accuracy                           0.96      1293
   macro avg       0.96      0.95      0.96      1293
weighted avg       0.96      0.96      0.96      1293



Support Vector Machine algorithm is more accurate than KNN algorithm